version: '3'
services:
  ui:
    build: exec-ui
    ports:
      - "4200:4200"

  api:
    build: 
      context: exec-api
      args:
        JAR_FILE: "./target/exec-api.jar"
    ports:
      - "8080:8080"
    volumes:
      - "/Users//dev/config:/var/app/config"
